version: '3.4'

services:
  bang.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "15000:80"
    build:
      context: .
      dockerfile: Services/Bang/Bang.API/Dockerfile

  sqlserver:    
    environment:
      SA_PASSWORD: "BangAdmin123"
      ACCEPT_EULA: "Y"