version: '3.4'

services:
  apigateway.api:
    image: ${DOCKER_REGISTRY-}apigatewayapi

  useridentity.api:
    image: ${DOCKER_REGISTRY-}useridentityapi
    depends_on:
      - sqlserver

  bang.api:
    image: ${DOCKER_REGISTRY-}bangapi
    depends_on:
      - sqlserver

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"